<Project>
  <PropertyGroup>
		<RWEEVersion>1.1.6</RWEEVersion>
		<RWMMVersion>0.0.4</RWMMVersion>
    <Company>RWEE</Company>
    <Authors>RWEE</Authors>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
		<GamePath>C:\Program Files (x86)\Steam\steamapps\common\Star Valor</GamePath>
		<RWEEPatcher></RWEEPatcher>
		<RWEEPluginDir></RWEEPluginDir>
		<RWMMPatcher></RWMMPatcher>
		<RWMMPluginDir>RedWizardsModManager.Plugin</RWMMPluginDir>
  </PropertyGroup>

	<Target Name="GenerateVersionsCode" BeforeTargets="BeforeCompile">
		<WriteLinesToFile
			File="$(MSBuildThisFileDirectory)Shared\Versions.cs"
			Overwrite="true"
			Encoding="UTF-8"
			Lines="
namespace RW
{
	static public class Versions
	{
		public const string RWEE = &quot;$(RWEEVersion)&quot; %3B
		public const string RWMM = &quot;$(RWMMVersion)&quot; %3B
	}
}" />
	</Target>
</Project>